version: "3.9" 
name: ${COMPOSE_PROJECT_NAME:-api-mercadolibre}
services: 
  api: 
    container_name: ${CONTAINER_NAME:?container name is not defined...} 
    build: 
      context: . 
    env_file: .env
    environment:
      - TZ=America/Argentina/Buenos_Aires
    restart: always
    ports:
      - ${API_PORT:-8080}:8080
    volumes:
      - .src/:/build/src:rw
    extra_hosts:
      - host.docker.internal:host-gateway